[project.extra]
homepage = "https://flyatcsim.club"

[project.theme]  # 项目主题
variant = "modern"
language = "zh"
direction = "ltr"  # left to right 自作向右 阅读

features = [
    # 代码框
    "content.action.edit",
    "content.action.view",
    "content.action.edit",
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",

    # 导航栏
    "navigation.path",
#    "navigation.instant",
#    "navigation.instant.prefetch",
#    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.sections",
    "navigation.expand",
    "navigation.top",  # 返回顶部按钮
    "navigation.tabs",  # 将导航栏放置于顶部
    "navigation.footer",
    "navigation.indexes",

    # 搜索
    "search.highlight",
    "search.suggest",
    "search.highlight",
    "search.share",

]


[project]
docs_dir = "docs"

site_name = "China Sector Package·文档站"
site_description = "Use Markdown language to finish the Operating document."
site_url = "https://docs.apocfly.com"

repo_url = "https://github.com/Flyatcsim-Sector-Studio/China-Sector-Package-Tutorial/"
repo_name = "Flyatcsim-Sector-Studio/China-Sector-Package-Tutorial"
edit_uri = "edit/main/docs/"

# CC BY-SA 4.0
site_author = "Master Gui, Xiao Zhang"
copyright = """Copyright (c) 2026 <a href="https://github.com/supermastergui" target="_blank" rel="noopener noreferrer">Master Gui</a> & <a href="https://github.com/XiaoZhang-store" target="_blank" rel="noopener noreferrer">Xiao Zhang</a> 保留所有未明示授予的权利。 <br> Intended for simulator only, Do not use for reality | 仅供模拟飞行使用，请勿用于真实飞行"""

# extra_javascript = ["javascripts/feedback.js"]  # 反馈js

# use_directory_urls = false # 在任意文档的URL后加入.html, 避免错误

extra_css = [
    "stylesheets/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css"
] # 引入外部css

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]

[project.extra.consent]
title = "Cookie 许可"
description = """
    我们使用Cookie来识别您的重复访问和偏好，并衡量我们文档的有效性以及用户是否能找到他们正在搜索的内容。在您同意的情况下，您正在帮助我们改进我们的文档。
"""

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Flyatcsim-Sector-Studio/China-Sector-Package-Tutorial"

[[project.extra.social]]
icon = "fontawesome/brands/qq"
link = "https://qm.qq.com/q/75BVQn7X56"

# Markwodn 扩展
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "underscore"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
key_map= {"lbutton_cn" = "鼠标左键", "rbutton_cn" = "鼠标右键"}
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]